title: [Chorus Castelli]
description: [Komorní pěvecký sbor při ZUŠ Uherské Hradiště]
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one